In [28]:
import pandas as pd 
import pathlib
import win32com.client as win32

In [29]:
emails = pd.read_excel(r'Bases de Dados\Emails.xlsx')
lojas = pd.read_csv(r'Bases de Dados\Lojas.csv', sep=';', encoding='latin1')
vendas = pd.read_excel(r'Bases de Dados\Vendas.xlsx')

display(emails.head())
display(lojas.head())
display(vendas.head())

,Loja,Gerente,E-mail
0,Iguatemi Esplanada,Helena,pythonimpressionador+helena@gmail.com
1,Shopping Midway Mall,Alice,pythonimpressionador+alice@gmail.com
2,Norte Shopping,Laura,pythonimpressionador+laura@gmail.com
3,Shopping Iguatemi Fortaleza,Manuela,pythonimpressionador+manuela@gmail.com
4,Shopping União de Osasco,Valentina,pythonimpressionador+valentina@gmail.com

   ID Loja                         Loja
0        1           Iguatemi Esplanada
1        2         Shopping Midway Mall
2        3               Norte Shopping
3        4  Shopping Iguatemi Fortaleza
4        5     Shopping União de Osasco

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,1,Sapato Estampa,1,358,358
1,1,2019-01-01,1,Camiseta,2,180,360
2,1,2019-01-01,1,Sapato Xadrez,1,368,368
3,2,2019-01-02,3,Relógio,3,200,600
4,2,2019-01-02,3,Chinelo Liso,1,71,71

In [30]:
vendas = vendas.merge(lojas, on='ID Loja')
display(vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2019-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
3,2,2019-01-02,3,Relógio,3,200,600,Norte Shopping
4,2,2019-01-02,3,Chinelo Liso,1,71,71,Norte Shopping
...,...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204,Center Shopping Uberlândia
100995,69996,2019-12-26,17,Mochila,4,270,1080,Center Shopping Uberlândia
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87,Center Shopping Uberlândia
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108,Ribeirão Shopping
100998,69997,2019-12-26,11,Short Linho,2,133,266,Ribeirão Shopping

In [31]:
dic_lojas = {}

for loja in lojas['Loja']:
    dic_lojas[loja] = vendas.loc[vendas['Loja']== loja, :]
#Exemplo 
display(dic_lojas['Iguatemi Campinas'])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
10,8,2019-01-02,24,Terno Estampa,5,706,3530,Iguatemi Campinas
21,17,2019-01-02,24,Chinelo Liso,1,71,71,Iguatemi Campinas
195,143,2019-01-02,24,Pulseira,3,70,210,Iguatemi Campinas
230,166,2019-01-02,24,Cinto Xadrez,1,215,215,Iguatemi Campinas
243,176,2019-01-02,24,Cinto Listrado,1,214,214,Iguatemi Campinas
...,...,...,...,...,...,...,...,...
100904,69934,2019-12-25,24,Chinelo Estampa,3,74,222,Iguatemi Campinas
100905,69934,2019-12-25,24,Camisa Xadrez,2,105,210,Iguatemi Campinas
100906,69934,2019-12-25,24,Tênis Liso,2,266,532,Iguatemi Campinas
100907,69934,2019-12-25,24,Casaco Listrado,1,269,269,Iguatemi Campinas
100912,69939,2019-12-25,24,Bermuda Liso,5,157,785,Iguatemi Campinas

In [32]:
indicador_do_dia = vendas['Data'].max()
print(indicador_do_dia)
print(f'{indicador_do_dia.day}/{indicador_do_dia.month}')

2019-12-26 00:00:00
26/12

In [33]:
#Criar e salvar pastas de backup das lojas
backup = pathlib.Path(r'Backup Arquivos Lojas')

arquivos_backup = backup.iterdir()
list_arquivos_backup = [arquivo.name for arquivo in arquivos_backup]

for loja in dic_lojas:
    if loja not in list_arquivos_backup:
        nova_pasta = backup / loja
        nova_pasta.mkdir()
    
    nome_arquivo = (f'{indicador_do_dia.month}_{indicador_do_dia.day}_{loja}.xlsx') 
    local_do_arquivo = backup / loja / nome_arquivo
    dic_lojas[loja].to_excel(local_do_arquivo)

In [34]:
#Metas anuais e diárias 
meta_faturamento_diaria = 1000
meta_faturamento_anual = 165000
meta_qtdeprodutos_diaria = 4
meta_qtdeprodutos_anual = 120
meta_ticketmedio_diario = 500
meta_ticketmedio_anual = 500

In [11]:
for loja in dic_lojas:
  
  vendas_loja = dic_lojas[loja]
  vendas_diarias_loja = vendas_loja.loc[vendas_loja['Data']==indicador_do_dia, :]

  #Calculando os faturamentos
  faturamento_anual = vendas_loja['Valor Final'].sum()
  faturamento_diario = vendas_diarias_loja['Valor Final'].sum()

  #Calculando a diversidade de produtos
  qtde_produtos_anual = len(vendas_loja['Produto'].unique())
  qtde_produtos_diario = len(vendas_diarias_loja['Produto'].unique())

  #Calculando o ticket médio 
  valor_venda = vendas_loja.groupby('Código Venda').sum(numeric_only=True)
  ticket_medio_anual = valor_venda['Valor Final'].mean()
  valor_venda_diaria = vendas_diarias_loja.groupby('Código Venda').sum(numeric_only=True)
  ticket_medio_diario = valor_venda_diaria['Valor Final'].mean()

  #Criando o envio do e-mail e das mensagens que serão enviadas para o e-mail de cada pessoa.

  outlook = win32.Dispatch('outlook.application')

  nome =emails.loc[emails['Loja']==loja,'Gerente'].values[0]
  mail = outlook.CreateItem(0)
  mail.To = emails.loc[emails['Loja']==loja, 'E-mail'].values[0]
  mail.Subject = f'OnePage Dia {indicador_do_dia.day}/{indicador_do_dia.month} - Loja {loja}'

  if faturamento_diario >= meta_faturamento_diaria:
    cor_fat_diario = 'green'
  else: 
    cor_fat_diario = 'red'
  if faturamento_anual >= meta_faturamento_anual:  
    cor_fat_anual = 'green'
  else:
    cor_fat_anual = 'red'
  if qtde_produtos_diario >= meta_qtdeprodutos_diaria:
    cor_qtde_diaria = 'green'
  else: 
    cor_qtde_diaria = 'red'
  if qtde_produtos_anual >= meta_qtdeprodutos_anual:
    cor_qtde_anual = 'green'
  else: 
    cor_qtde_anual = 'red'
  if ticket_medio_diario >= meta_ticketmedio_diario:
    cor_ticket_diario = 'green'
  else: 
    cor_ticket_diario = 'red'
  if ticket_medio_anual >= meta_ticketmedio_anual:
    cor_ticket_anual = 'green'
  else:
    cor_ticket_anual = 'red'

  mail.HTMLBody = f''' 
  <p> Bom dia, {nome}</p>

  <p> O Resultado de ontem <strong>({indicador_do_dia.day}/{indicador_do_dia.month})</strong> da <strong>Loja {loja}</strong>  foi:</p> 

  <table>
        <tr>
          <th>Indicador</th>
          <th>Valor Diário</th>
          <th>Meta Diária</th>
          <th>Cenário Diário</th>
        </tr>
        <tr>
          <td>Faturamento</td>
          <td style="text-align: center">R${faturamento_diario:.2f}</td>
          <td style="text-align: center">R${meta_faturamento_diaria:.2f}</td>
          <td style="text-align: center"><font color="{cor_fat_diario}">◙</font></td>
        </tr>
        <tr>
          <td>Diversidade de Produtos</td>
          <td style="text-align: center">{cor_qtde_diaria}</td>
          <td style="text-align: center">{meta_qtdeprodutos_diaria}</td>
          <td style="text-align: center"><font color="{cor_qtde_diaria}">◙</font></td>
        </tr>
        <tr>
          <td>Ticket Médio</td>
          <td style="text-align: center">R${ticket_medio_diario:.2f}</td>
          <td style="text-align: center">R${meta_ticketmedio_diario:.2f}</td>
          <td style="text-align: center"><font color="{cor_ticket_diario}">◙</font></td>
        </tr>
      </table>
      <br>
      <table>
        <tr>
          <th>Indicador</th>
          <th>Valor Anual</th>
          <th>Meta Anual</th>
          <th>Cenário Anual</th>
        </tr>
        <tr>
          <td>Faturamento</td>
          <td style="text-align: center">R${faturamento_anual:.2f}</td>
          <td style="text-align: center">R${meta_faturamento_anual:.2f}</td>
          <td style="text-align: center"><font color="{cor_fat_anual}">◙</font></td>
        </tr>
        <tr>
          <td>Diversidade de Produtos</td>
          <td style="text-align: center">{qtde_produtos_anual}</td>
          <td style="text-align: center">{meta_qtdeprodutos_anual}</td>
          <td style="text-align: center"><font color="{cor_qtde_anual}">◙</font></td>
        </tr>
        <tr>
          <td>Ticket Médio</td>
          <td style="text-align: center">R${ticket_medio_anual:.2f}</td>
          <td style="text-align: center">R${meta_ticketmedio_anual:.2f}</td>
          <td style="text-align: center"><font color="{cor_ticket_anual}">◙</font></td>
        </tr>
      </table>
          

  <p> Segue em anexo a planilha com todos os dados para mais detalhes.</p> 

  <p> Qualquer duvida estou à disposição.</p>
  <p> Att., Murilo</p>  
  '''

  attachment  = pathlib.Path.cwd() / backup / loja / f'{indicador_do_dia.month}_{indicador_do_dia.day}_{loja}.xlsx'
  mail.Attachments.Add(str(attachment))

  mail.Send()
  print(f'E-mail da Loja {loja} enviado.')

E-mail da Loja Iguatemi Esplanada enviado
E-mail da Loja Shopping Midway Mall enviado
E-mail da Loja Norte Shopping enviado
E-mail da Loja Shopping Iguatemi Fortaleza enviado
E-mail da Loja Shopping União de Osasco enviado
E-mail da Loja Shopping Center Interlagos enviado
E-mail da Loja Rio Mar Recife enviado
E-mail da Loja Salvador Shopping enviado
E-mail da Loja Rio Mar Shopping Fortaleza enviado
E-mail da Loja Shopping Center Leste Aricanduva enviado
E-mail da Loja Ribeirão Shopping enviado
E-mail da Loja Shopping Morumbi enviado
E-mail da Loja Parque Dom Pedro Shopping enviado
E-mail da Loja Bourbon Shopping SP enviado
E-mail da Loja Palladium Shopping Curitiba enviado
E-mail da Loja Passei das Águas Shopping enviado
E-mail da Loja Center Shopping Uberlândia enviado
E-mail da Loja Shopping Recife enviado
E-mail da Loja Shopping Vila Velha enviado
E-mail da Loja Shopping SP Market enviado
E-mail da Loja Shopping Eldorado enviado
E-mail da Loja Shopping Ibirapuera enviado
E-mail da Loja Novo Shopping Ribeirão Preto enviado
E-mail da Loja Iguatemi Campinas enviado
E-mail da Loja Shopping Barra enviado

In [35]:
faturamento_lojas = vendas.groupby('Loja')[['Valor Final']].sum()
faturamento_lojas_anual= faturamento_lojas.sort_values(by='Valor Final', ascending=False)
display(faturamento_lojas_anual)

nome_arquivo = (f'{indicador_do_dia.month}_{indicador_do_dia.day}_Ranking Anual.xlsx')
faturamento_lojas_anual.to_excel(rf'Backup Arquivos Lojas\{nome_arquivo}')

vendas_diarias = vendas.loc[vendas['Data']==indicador_do_dia, :]
faturamento_lojas_diario = vendas_diarias.groupby('Loja')[['Valor Final']].sum()
faturamento_lojas_diario= faturamento_lojas_diario.sort_values(by='Valor Final', ascending=False)
display(faturamento_lojas_diario)

nome_arquivo = (f'{indicador_do_dia.month}_{indicador_do_dia.day}_Ranking Diário.xlsx')
faturamento_lojas_diario.to_excel(rf'Backup Arquivos Lojas\{nome_arquivo}')

                                  Valor Final
Loja
Iguatemi Campinas                     1762419
Shopping Vila Velha                   1731167
Bourbon Shopping SP                   1726110
Rio Mar Recife                        1722766
Shopping SP Market                    1721763
Palladium Shopping Curitiba           1721120
Norte Shopping                        1711968
Ribeirão Shopping                     1707122
Iguatemi Esplanada                    1699681
Rio Mar Shopping Fortaleza            1698430
Shopping Center Leste Aricanduva      1682870
Novo Shopping Ribeirão Preto          1678225
Shopping Iguatemi Fortaleza           1674824
Center Shopping Uberlândia            1668921
Shopping União de Osasco              1663770
Shopping Barra                        1653103
Passei das Águas Shopping             1649014
Shopping Eldorado                     1648111
Salvador Shopping                     1646739
Shopping Center Interlagos            1640486
Shopping Ibirapuera                   1635060
Parque Dom Pedro Shopping             1631630
Shopping Recife                       1624879
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444

                                  Valor Final
Loja
Salvador Shopping                        3950
Novo Shopping Ribeirão Preto             3400
Center Shopping Uberlândia               2651
Shopping Eldorado                        2391
Shopping Center Interlagos               1582
Shopping Recife                          1366
Norte Shopping                           1259
Shopping União de Osasco                 1207
Shopping Vila Velha                       937
Bourbon Shopping SP                       676
Ribeirão Shopping                         650
Shopping Center Leste Aricanduva          485
Palladium Shopping Curitiba               381
Rio Mar Shopping Fortaleza                368
Shopping Midway Mall                      170
Shopping Ibirapuera                       118

In [37]:
outlook = win32.Dispatch('outlook.application')

mail = outlook.CreateItem(0)
mail.To = emails.loc[emails['Loja']=='Diretoria', 'E-mail'].values[0]
mail.Subject = f'Ranking Dia {indicador_do_dia.day}/{indicador_do_dia.month}'
mail.Body = f''' 
Prezados, bom dia

Melhor Loja em faturamento Diário: Loja{faturamento_lojas_diario.index[0]} com faturamento R${faturamento_lojas_diario.iloc[0,0]:.2f}
Pior Loja em fatuamento Diário: Loja {faturamento_lojas_diario.index[-1]} com faturamento R${faturamento_lojas_diario.iloc[-1,0]:.2f}

Melhor Loja em faturamento Anual: Loja{faturamento_lojas_anual.index[0]} com faturamento R${faturamento_lojas_anual.iloc[0,0]:.2f}
Pior Loja em fatuamento Anual: Loja {faturamento_lojas_anual.index[-1]} com faturamento R${faturamento_lojas_anual.iloc[-1,0]:.2f}

Segue em anexo os rankings do ano e do dia de todas as lojas.

Qualquer dúvida estou á disposição.
Att.,
Murilo
'''

attachment  = pathlib.Path.cwd() / backup / f'{indicador_do_dia.month}_{indicador_do_dia.day}_Ranking Anual.xlsx'
mail.Attachments.Add(str(attachment))
attachment  = pathlib.Path.cwd() / backup / f'{indicador_do_dia.month}_{indicador_do_dia.day}_Ranking Diário.xlsx'
mail.Attachments.Add(str(attachment))


mail.Send()
print(f'E-mail da Diretoria enviado.')

E-mail da Diretoria enviado.